name: flutter_tdd_q
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  cloud_firestore: ^3.1.10
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.1.2
  flutter_html: ^2.2.1
  flutter_riverpod: ^1.0.3
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  hooks_riverpod: ^1.0.3
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  riverpod: ^1.0.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  anim_search_bar: ^2.0.2
  flash: ^2.0.3+2
  custom_radio_grouped_button: ^2.1.2
  firebase_auth_mocks: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: null
  build_runner: ^2.1.8
  lint: ^1.8.2
  auto_route_generator: ^3.2.3

  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  injectable_generator: null
  mockito: ^5.1.0
  state_notifier_test: ^0.0.5
  retrofit_generator: null

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    dev:
      app:
        name: "Q recipes"

      android:
        applicationId: "agency.q.flutterTdd.dev"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "agency.q.flutterTdd.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    staging:
      app:
        name: "Flutter TDD Staging"

      android:
        applicationId: "agency.q.flutterTdd.staging"
        firebase:
          config: ".firebase/staging/google-services.json"
      ios:
        bundleId: "agency.q.flutterTdd.staging"
        firebase:
          config: ".firebase/staging/GoogleService-Info.plist"

    prod:
      app:
        name: "Flutter TDD"

      android:
        applicationId: "agency.q.flutterTdd"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "agency.q.flutterTdd"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"
