name: flutter_tdd_q
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.4.0
  cloud_firestore: ^4.8.1
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.2.1+1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.2.1
  flutter_html: ^3.0.0-beta.2
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  anim_search_bar: ^2.0.3
  flash: ^2.0.5+1
  custom_radio_grouped_button: ^2.2.0
  firebase_auth_mocks: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: null
  build_runner: ^2.4.5
  lint: ^2.1.2
  auto_route_generator: null

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  mockito: ^5.4.2
  state_notifier_test: ^0.0.10
  retrofit_generator: null

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    dev:
      app:
        name: "Q recipes"

      android:
        applicationId: "agency.q.flutterTdd.dev"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "agency.q.flutterTdd.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    staging:
      app:
        name: "Flutter TDD Staging"

      android:
        applicationId: "agency.q.flutterTdd.staging"
        firebase:
          config: ".firebase/staging/google-services.json"
      ios:
        bundleId: "agency.q.flutterTdd.staging"
        firebase:
          config: ".firebase/staging/GoogleService-Info.plist"

    prod:
      app:
        name: "Flutter TDD"

      android:
        applicationId: "agency.q.flutterTdd"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "agency.q.flutterTdd"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"
