name: flutter_tdd_q
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  cloud_firestore: ^4.1.0
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.1.5
  flutter_html: ^3.0.0-alpha.6
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hooks_riverpod: ^2.1.1
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  anim_search_bar: ^2.0.2
  flash: ^2.0.5
  custom_radio_grouped_button: ^2.1.2+2
  firebase_auth_mocks: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: null
  build_runner: 2.3.0
  lint: ^2.0.1
  auto_route_generator: 5.0.2

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  injectable_generator: null
  mockito: ^5.3.2
  state_notifier_test: ^0.0.9
  retrofit_generator: null

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    dev:
      app:
        name: "Q recipes"

      android:
        applicationId: "agency.q.flutterTdd.dev"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "agency.q.flutterTdd.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    staging:
      app:
        name: "Flutter TDD Staging"

      android:
        applicationId: "agency.q.flutterTdd.staging"
        firebase:
          config: ".firebase/staging/google-services.json"
      ios:
        bundleId: "agency.q.flutterTdd.staging"
        firebase:
          config: ".firebase/staging/GoogleService-Info.plist"

    prod:
      app:
        name: "Flutter TDD"

      android:
        applicationId: "agency.q.flutterTdd"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "agency.q.flutterTdd"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"
